/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: Helen.twee
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @Helen: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@Helen()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage0_Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #0: Helen

	void passage0_Init()
	{
		this.Passages[@"Helen"] = new StoryPassage(@"Helen", new string[]{  }, passage0_Main);
	}

	IStoryThread passage0_Main()
	{
		if (visited("Helen") == 1)
		{
			yield return lineBreak();
			yield return text(@"    Helen: Creía que no se iba a acabar nunca, te debo una");
			setanim("Helen", "Deny");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return text(@"Helen: Cada vez los turnos son más largos");
		yield return lineBreak();
		yield return text(@"Helen: Con este ritmo voy a acabar en la zona de reformación");
		yield return lineBreak();
		yield return link(@"Voy a liberaros", @"Liberar", null);
		yield return lineBreak();
		yield return link(@"Nos vemos", @"Salir", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #1: Liberar

	void passage1_Init()
	{
		this.Passages[@"Liberar"] = new StoryPassage(@"Liberar", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"Helen: Ojalá..");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Salir

	void passage2_Init()
	{
		this.Passages[@"Salir"] = new StoryPassage(@"Salir", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"Helen: (...)");
		yield return lineBreak();
		yield break;
	}


}